import Head from "next/head";
import Link from "next/link";
//import styles from "@/styles/Home.module.css";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>トップ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div style={{
        background: "linear-gradient(180deg, #e8f5e9, #fffde7)",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center"
      }}>
        <div style={{
          background: "white",
          padding: "50px",
          borderRadius: "30px",
          boxShadow: "0px 8px 16px rgba(0,0,0,0.1)",
          textAlign: "center",
          width: "90%",
          maxWidth: "500px"
        }}>
          <div style={{
            backgroundColor: "#c8e6c9",
            //width: "40px",
            //height: "40px",
            borderRadius: "50%",
            margin: "0 auto 20px auto"
          }}></div>
          <h1 style={{ color: "#388e3c", fontWeight: "bold", marginBottom: "15px" }}>Welcome to Chat!</h1>
          <p style={{ color: "#555", marginBottom: "25px", fontSize: "16px" }}>Welcome to Chat! This is the Chat Home page.</p>

          <div style={{ display: "flex", justifyContent: "center", gap: "15px" }}>
            <Link href="/signup" passHref>
              <button style={{
                backgroundColor: "#388e3c",
                color: "#fff",
                padding: "10px 20px",
                borderRadius: "30px",
                border: "none",
                cursor: "pointer",
                transition: "all 0.3s",
                boxShadow: "0 4px 8px rgba(0,0,0,0.1)"
              }}>
                アカウントを作成する
              </button>
            </Link>
            <Link href="/login" passHref>
              <button style={{
                backgroundColor: "#388e3c",
                color: "#fff",
                padding: "10px 20px",
                borderRadius: "30px",
                border: "none",
                cursor: "pointer",
                transition: "all 0.3s",
                boxShadow: "0 4px 8px rgba(0,0,0,0.1)"
              }}>
                ログインする
              </button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
